### PR TITLE
release: 1.6.0

### PR DESCRIPTION
**Pull request by curbengh**
Bump minor (instead of patch) due a minor breaking change introduced in https://github.com/hexojs/hexo-util/pull/130

### CODE REVIEW

**Comment by SukkaW** [comment]
IMHO, 1.6.0 could include #134 .

**Comment by SukkaW** [comment]
Also, I will address #136 recently. Maybe it could be introduced in 1.6.0 as well.

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-util/issues/136 is not urgent and requires a new dep, I prefer to defer it later.

1.6.0 includes several urgent fixes and I would like to release it asap.

**Comment by curbengh** [comment]
I would like to include https://github.com/hexojs/hexo-util/pull/138 as it's a trivial fix.

**Comment by curbengh** [comment]
@hexojs/core 

This release is needed to fix CI regression https://github.com/hexojs/hexo/issues/3833.

**Comment by curbengh** [comment]
https://www.npmjs.com/package/hexo-util/v/1.6.0

**Pull request merged**
