### PR TITLE
Bump Eslint & drop nodejs 6

### PR DESCRIPTION
**Pull request by tomap**
Last version of eslint does not support nodejs 6

### CODE REVIEW

**Comment by tomap** [comment]
To be able to complete https://github.com/hexojs/hexo-util/pull/60
Related to https://github.com/hexojs/hexo/issues/3508

**Comment by curbengh** [comment]
Is there any prerequisite? I can't test it locally,

```
$ npm test
hexo-util/highlight_alias.json: Unexpected end of JSON input
```

---

For the Node 12 issue, try
```js
  it('str must be a string', () => {
    const errorCallback = sinon.spy(err => {
      err.should.have.property('message', 'str must be a string!');
    });

    try {
      highlight();
    } catch (err) {
      errorCallback(err);
    }

    errorCallback.calledOnce.should.be.true;
  });
```

**Comment by tomap** [comment]
The two failing tests are those ones:
``` 
it('verbose - stdout', () => {
    const spawn = rewire('../../lib/spawn');
    const stdoutCache = new CacheStream();
    const stderrCache = new CacheStream();
    const content = 'something';

    spawn.__set__('process', {
      stdout: stdoutCache,
      stderr: stderrCache
    });

    return spawn('echo', [content], {
      verbose: true
    }).then(() => {
      stdoutCache.getCache().toString('utf8').trim().should.eql(content);
    });
  });

  it('verbose - stderr', () => {
    const spawn = rewire('../../lib/spawn');
    const stdoutCache = new CacheStream();
    const stderrCache = new CacheStream();

    spawn.__set__('process', {
      stdout: stdoutCache,
      stderr: stderrCache
    });

    return spawn('cat', ['nothing'], {
      verbose: true
    }).catch(() => {
      stderrCache.getCache().toString('utf8').trim().should
        .eql('cat: nothing: No such file or directory');
    });
  });
```

**Comment by tomap** [comment]
Fixed using the comments in this issue:
https://github.com/jhnns/rewire/issues/167

**Pull request merged**
