### PR TITLE
fix: avoid overriding Transform.destroy() method

### PR DESCRIPTION
**Pull request by curbengh**
fix compatibility with Node 14

https://github.com/hexojs/hexo/issues/4260#issuecomment-618483486

### CODE REVIEW

**Comment by curbengh** [comment]
Introduce regression in Node < 14.

**Comment by curbengh** [comment]
Tested Node 10, 12, 13 and 14 on dummy blog using `hexo g --debug`, no errors and resolved empty files issue.

**Comment by stevenjoezhang** [comment]
Confirm that it is working properly now.
However, after removing the definition of `destroy` method, `cacheStream._cache` will not be deleted, which means that the resource is actually processed by JavaScript garbage collection, not `cacheStream.destroy();` here:

https://github.com/hexojs/hexo/blob/b60f815b975178ee1c907a92e5a1403830e56f37/lib/plugins/console/generate.js#L68

**Comment by SukkaW** [comment]
> which means that the resource is actually processed by JavaScript garbage collection

Will it cause memory leak?

**Comment by SukkaW** [comment]
Verified in https://github.com/hexojs/hexo/pull/4264

**Comment by curbengh** [comment]
> cacheStream._cache will not be deleted...the resource is actually processed by JavaScript garbage collection

Meaning `destroy()` triggers the garbage collection to clean up `_cache`? Will `_cache` get cleaned up and not cause memory leakage?

**Comment by SukkaW** [comment]
> I assume `destroy()` is working then?

Yes. If it is not working, there might be huge memory consumption.

**Pull request merged**
