### PR TITLE
test: improve coverage

### PR DESCRIPTION
**Pull request by D-Sketon**
https://github.com/hexojs/hexo/issues/3984

### CODE REVIEW

**Comment by D-Sketon** [comment]
> TypeScript 5.1 now ships JavaScript functionality that was introduced in ECMAScript 2020. As a result, at minimum TypeScript must be run in a reasonably modern runtime. For most users, this means TypeScript now only runs on Node.js 14.17 and later.

should we remove Tester using Node 12.x ?

**Comment by SukkaW** [comment]
> > TypeScript 5.1 now ships JavaScript functionality that was introduced in ECMAScript 2020. As a result, at minimum TypeScript must be run in a reasonably modern runtime. For most users, this means TypeScript now only runs on Node.js 14.17 and later.
> 
> should we remove Tester using Node 12.x ?

Sure! And `hexo-util@3` has dropped Node.js 12 already, for some reason we forgot to remove the Node.js 12 test runner.

**Comment by SukkaW** [comment]
@D-Sketon 

https://github.com/hexojs/hexo-util/pull/321 has been merged. Would you like to rebase your this PR?

**Comment by D-Sketon** [comment]
> @D-Sketon
> 
> #321 has been merged. Would you like to rebase your this PR?

ok

**Review by SukkaW — DISMISSED** [review]

**Review by SukkaW — APPROVED** [review]

**Review by uiolee — DISMISSED** [review]

**Review by uiolee — APPROVED** [review]

**Review by uiolee — APPROVED** [review]

**Comment by stevenjoezhang** [comment]
Superseded by https://github.com/hexojs/hexo-util/pull/354

**Pull request closed without merging**
