### PR TITLE
feat(highlight): adjust the layout of the highlight code block

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## Current behavior
```html
<tr>
  <td class="gutter"><pre>
    <span class="line">1</span>
    <br>
    <span class="line">2</span>
    <br>
    <span class="line">3</span>
  </pre></td>

  <td class="code"><pre>
    <span class="line">hello, world</pre>
    <br>
    <span class="line">hello, world</span>
    <br>
    <span class="line">hello, world</span>
  </pre></td>
</tr>
```

## New behavior
```html
<tr>
  <td class="gutter"><pre>
    <span class="line">1</span>
  </pre></td>
  <td class="code"><pre>
    <span class="line">hello, world</pre>
  </td>
</tr>

<tr>
  <td class="gutter"><pre>
    <span class="line">2</span>
  </pre></td>
  <td class="code"><pre>
    <span class="line">hello, world</pre>
  </td>
</tr>

<tr>
  <td class="gutter"><pre>
    <span class="line">3</span>
  </pre></td>
  <td class="code"><pre>
    <span class="line">hello, world</pre>
  </td>
</tr>
```

### CODE REVIEW

**Comment by SukkaW** [comment]
Currently I am working on a new Hexo theme, and highlight style problem just nearly makes me mad. I am sure this PR would help, but I am wonder if this will significantly increase output HTML size.

**Comment by SukkaW** [comment]
Also, the test case needs to be updated in order to pass the Travis CI test.

**Comment by stevenjoezhang** [comment]
Travis CI's error report has been fixed.

The main idea of this PR is: it's a bit strange to use `<br>` inside the `<table>` element. Use more `<tr>` elements can make the structure of the table more logical.

**Comment by stevenjoezhang** [comment]
@SukkaW @curbengh @jiangtj 
Talking about backward compatible, I found that I have made a mistake. This PR might make the empty lines disappear in `<table>` if `highlight.line_number` is disabled in `_config.yml`.

https://github.com/hexojs/hexo-util/blob/e736e1bf9fa72a9f57cae82bf5f46a3a6cb56a33/lib/highlight.js#L61-L72

And here's the solution - it's necessary to insert a `<br>` tag if the line is empty.

```diff
function formatLine(line, lineno, marked, options) {
+  line = line || '<br>';
  const useHljs = options.hljs || false;
  let res = useHljs ? '' : '<span class="line';
  if (marked.includes(lineno)) {
    // Handle marked lines.
    res += useHljs ? `<mark>${line}</mark>` : ` marked">${line}</span>`;
  } else {
    res += useHljs ? line : `">${line}</span>`;
  }


  return res;
}
```

**Comment by curbengh** [comment]
I see, I was wondering why empty line is removed in https://deploy-preview-1241--hexo-site.netlify.com/news/2019/12/09/hexo-4-1-released/ when previewing https://github.com/hexojs/site/pull/1241 .

Please submit a PR.

**Pull request merged**
