### PR TITLE
release: 1.9.0

### PR DESCRIPTION
**Pull request by YoshinoriN**
#180

### CODE REVIEW

**Comment by SukkaW** [comment]
https://github.com/hexojs/hexo/issues/4130

I'd like to include a fix for that issue in 1.9.0.

**Comment by SukkaW** [comment]
The changelog could be:

### Features

- [`prismHighlight()`](https://github.com/hexojs/hexo-util#prismhighlightstr-options) utility (#168, #172, #177)

### Fixes

- fix(htmlTag): String() before match() for scalar values (#176)
- fix(isExternalLink): handle invalid url

### Changes

- refactor: optimize cache for `url_for()` & `full_url_for()` (#170)
- test(mocha): json to yml
-

**Comment by SukkaW** [comment]
@YoshinoriN @curbengh hexo-util 1.9.0 should be ready to go.

**Comment by YoshinoriN** [comment]
@SukkaW 
Would you please approve this PR?
I will release 1.9.0 :)

**Comment by SukkaW** [comment]
@YoshinoriN Approved.

**Comment by YoshinoriN** [comment]
published !! :sunglasses:

**Pull request merged**
