### PR TITLE
change divs in code blocks back to spans

### PR DESCRIPTION
**Pull request by greg-js**
For some reason I changed the spans to divs in a PR six months ago. Here's the fix to get rid of those divs again. Thanks to @csarron for letting me know the issue

### CODE REVIEW

**Comment by ahaasler** [comment]
I think this is what causes the empty lines error explained in meteor/hexo-theme-meteor#30 and discussed in hexojs/hexo#858 and hexojs/hexo#795.

It's easily fixed the way @tommy351 explains in hexojs/hexo-theme-landscape@ad0c9e95a13d33c12ffa257d44047b38a38fed6d, but I think this isn't something that themes should handle, being this a change all themes should make.

Quoting @0ssifrage:

> Adding css style for `.line` may be a solution, but it's hard to let all the themes change their css files.

**Comment by ahaasler** [comment]
I've been trying the change proposed by @tommy351 and the empty lines are not being copied with a Ctrl-C in the browser, because there's no content.

```
Line 1
Line 3
```

With this PR the empty lines are properly being copied by the browser:

```
Line 1

Line 3
```

I've also tested CSS content without success, because the CSS generated content is not selectable in a browser.

```css
.line:empty:after {
  content: '\000a';
}
```

It would be great if this PR could be merged and released.

**Comment by stubailo** [comment]
Any chance this could be merged? We have to pin to Hexo 3.2.0 in all of our sites because of this issue.

**Comment by poiru** [comment]
@NoahDragon Could we merge this?

**Comment by NoahDragon** [comment]
@poiru Thank for poking me. I will merge this issue.

**Comment by poiru** [comment]
@NoahDragon Thank you! Any Would you also be able to release a new version of `hexo-util`?

**Pull request merged**
