### PR TITLE
release: 2.4.0

### PR DESCRIPTION
**Pull request by curbengh**
https://github.com/hexojs/hexo-util/pull/227 https://github.com/hexojs/hexo-util/pull/229

### CODE REVIEW

**Comment by SukkaW** [comment]
Should #229 being considered as Breaking Changes?

`hexojs/hexo` has no `package.json` and `dependencies` is not pinned. If Hexo user installs the latest `hexo-util` their theme might be broken.

**Comment by curbengh** [comment]
> Should #229 being considered as Breaking Changes?

I believe I'm the only affected user 😅

**Comment by SukkaW** [comment]
> caption in `{ wrap: false }` config was only introduced recently in [2.2.0](https://github.com/hexojs/hexo-util/releases/tag/2.2.0) and it's not mentioned in hexo.io yet, so the breaking change is fairly minimal.

However there might be users who already uses caption white recently changed to `wrap: false`. Then `caption` could "come from nowhere" and break the theme.

**Comment by curbengh** [comment]
> ...already uses caption while recently changed to `wrap: false`,  then caption could "come from nowhere"

if they already use caption, shouldn't they expect caption to be displayed (as introduced in https://github.com/hexojs/hexo-util/pull/210)? Switching to `wrap: false` requires a significant change to the theme and hardly any theme supports it because it doesn't support line number.

It doesn't necessarily break the theme, more of a missing style. since caption in `wrap: false` was not supported previously, the only users who would style the caption are the ones who closely follow this repo, and if they already closely following, it should fairly trivial for them to update caption style after #229. #229 is indeed a breaking change for them, but the change is too minimal to justify bumping major.

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-util/releases/tag/2.4.0
https://www.npmjs.com/package/hexo-util/v/2.4.0

**Pull request merged**
