### PR TITLE
chore: bump version from 2.5.0 to 2.6.0

### PR DESCRIPTION
**Pull request by yoshinorin**
I'm going to release a new version after merge this PR.
Thank you :)

### CODE REVIEW

**Comment by tomap** [comment]
Shouldn't we merge https://github.com/hexojs/hexo-util/pull/266 and have a green ci before?

**Comment by yoshinorin** [comment]
> Shouldn't we merge #266 and have a green ci before?

The cause of this PR CI failure is unrelated  to # 266.
I don't know why assert error occur when upgrader rewire from `5.0.0` to `6.0.0` in #266. I think we need a time inspect it.

**Comment by yoshinorin** [comment]
@tomap 
I submitted #271 for green CI.
I assume the #266 will pass after merge & rebase #271.

**Comment by yoshinorin** [comment]
#271 CI is green.
Does someone would you please review #271?

I'm going to rebase this PR to master after merge #271.

Thank you :)

**Review by tomap — APPROVED** [review]

**Pull request merged**
