### PR TITLE
release: 1.6.2

### PR DESCRIPTION
**Pull request by curbengh**
emergency fix https://github.com/hexojs/hexo-util/pull/153

### CODE REVIEW

**Comment by SukkaW** [comment]
This also includes https://github.com/hexojs/hexo-util/pull/147

**Comment by SukkaW** [comment]
@curbengh Ready for a new Release.

**Comment by SukkaW** [comment]
Release Note:

## Features

- feat(deepMerge): bring up `deepMerge()` (#141)
  - This could be used to replace `lodash.merge`.
- feat(pretty_urls): bring up `prettyUrls()` (#152)

## Fixes

- fix(highlight): no need to disable 'wrap' when 'hljs' is enabled
- fix(url_for/full_url_for): do not process absolute url (#147)
- revert: feat(highlight): adjust the layout of the highlight code block
  - This commit reverts b201c8e

**Comment by SukkaW** [comment]
Since there are 2 features included in this version, bump version number to `1.7.0` might be better.

**Comment by curbengh** [comment]
> Since there are 2 features included in this version, bump version number to `1.7.0` might be better.

I forgot about that :sweat_smile:

**Pull request closed without merging**
